version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
    reviewers:
      - "yachiko"
    assignees:
      - "yachiko"
    open-pull-requests-limit: 5
    groups:
      go-modules:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
      - "ci"
    reviewers:
      - "yachiko"
    assignees:
      - "yachiko"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Europe/Warsaw"
    labels:
      - "dependencies"
    reviewers:
      - "yachiko"
    assignees:
      - "yachiko"
    open-pull-requests-limit: 5
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
