run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  gocyclo:
    min-complexity: 15
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/ahoma/spotalis
  
  revive:
    min-confidence: 0.8
  
  gomnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
  
  govet:
    check-shadowing: true
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: false
    require-explanation: true
    require-specific: true

linters:
  enable:
    - bodyclose
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gochecknoinits
    
    # Exclude generated files
    - path: zz_generated.*\.go
      linters:
        - goimports
        - gofmt
    
    # Exclude kubebuilder markers
    - source: "//\\+kubebuilder"
      linters:
        - revive
